export const restaurants = [
  {
    id: "rest_001",
    name: "Spice Route Kitchen",
    tagline: "Authentic Indian Flavors",
    rating: 4.7,
    totalReviews: 2847,
    deliveryTime: "20-30 min",
    deliveryFee: 39,
    distance: "2.4 km",
    isOpen: true,
    categories: ["Indian", "Biryani", "Chinese"],
    bannerImage: "https://images.unsplash.com/photo-1504674900247-0877df9cc836",
    offer: "50% OFF up to ₹120",
    address: "Saheed Nagar, Bhubaneswar",

    menu: [
      {
        id: "food_001",
        name: "Chicken Dum Biryani",
        description: "Long grain basmati rice with spicy chicken pieces.",
        price: 249,
        rating: 4.8,
        isVeg: false,
        bestseller: true,
        image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0",
      },

      {
        id: "food_002",
        name: "Paneer Butter Masala",
        description: "Creamy tomato gravy with soft paneer cubes.",
        price: 199,
        rating: 4.7,
        isVeg: true,
        bestseller: true,
        image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8",
      },

      {
        id: "food_003",
        name: "Butter Naan",
        description: "Soft tandoori naan brushed with butter.",
        price: 49,
        rating: 4.5,
        isVeg: true,
        bestseller: false,
        image: "https://images.unsplash.com/photo-1601050690597-df0568f70950",
      },
    ],
  },

  {
    id: "rest_002",
    name: "Burger Factory",
    tagline: "Loaded Burgers & Fries",
    rating: 4.5,
    totalReviews: 1930,
    deliveryTime: "15-25 min",
    deliveryFee: 29,
    distance: "1.8 km",
    isOpen: true,
    categories: ["Burgers", "Fast Food"],
    bannerImage: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd",
    offer: "Buy 1 Get 1 Free",
    address: "Patia, Bhubaneswar",

    menu: [
      {
        id: "food_004",
        name: "Classic Beef Burger",
        description: "Juicy beef patty with cheese and lettuce.",
        price: 299,
        rating: 4.9,
        isVeg: false,
        bestseller: true,
        image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd",
      },

      {
        id: "food_005",
        name: "Crispy Chicken Burger",
        description: "Crispy fried chicken with spicy mayo.",
        price: 249,
        rating: 4.6,
        isVeg: false,
        bestseller: true,
        image: "https://images.unsplash.com/photo-1550547660-d9450f859349",
      },

      {
        id: "food_006",
        name: "French Fries",
        description: "Golden crispy fries with peri peri seasoning.",
        price: 129,
        rating: 4.4,
        isVeg: true,
        bestseller: false,
        image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877",
      },
    ],
  },

  {
    id: "rest_003",
    name: "Pizza Hub",
    tagline: "Cheesy Happiness Delivered",
    rating: 4.6,
    totalReviews: 3201,
    deliveryTime: "25-35 min",
    deliveryFee: 49,
    distance: "3.2 km",
    isOpen: true,
    categories: ["Pizza", "Italian"],
    bannerImage: "https://images.unsplash.com/photo-1513104890138-7c749659a591",
    offer: "Flat ₹150 OFF",
    address: "Khandagiri, Bhubaneswar",

    menu: [
      {
        id: "food_007",
        name: "Margherita Pizza",
        description: "Classic cheese pizza with tomato basil sauce.",
        price: 349,
        rating: 4.7,
        isVeg: true,
        bestseller: true,
        image: "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3",
      },

      {
        id: "food_008",
        name: "Pepperoni Pizza",
        description: "Loaded with pepperoni and mozzarella cheese.",
        price: 449,
        rating: 4.8,
        isVeg: false,
        bestseller: true,
        image: "https://images.unsplash.com/photo-1628840042765-356cda07504e",
      },

      {
        id: "food_009",
        name: "Garlic Breadsticks",
        description: "Cheesy garlic bread with dipping sauce.",
        price: 159,
        rating: 4.5,
        isVeg: true,
        bestseller: false,
        image: "https://images.unsplash.com/photo-1573140247632-f8fd74997d5c",
      },
    ],
  },

  {
    id: "rest_004",
    name: "Sweet Cravings",
    tagline: "Desserts That Melt Hearts",
    rating: 4.9,
    totalReviews: 4120,
    deliveryTime: "10-20 min",
    deliveryFee: 25,
    distance: "900 m",
    isOpen: true,
    categories: ["Desserts", "Bakery"],
    bannerImage: "https://images.unsplash.com/photo-1551024601-bec78aea704b",
    offer: "Flat ₹100 OFF on Cakes",
    address: "Unit 4, Bhubaneswar",

    menu: [
      {
        id: "food_010",
        name: "Chocolate Lava Cake",
        description: "Warm chocolate cake with molten center.",
        price: 199,
        rating: 4.9,
        isVeg: true,
        bestseller: true,
        image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c",
      },

      {
        id: "food_011",
        name: "Red Velvet Pastry",
        description: "Soft creamy red velvet layered pastry.",
        price: 149,
        rating: 4.8,
        isVeg: true,
        bestseller: true,
        image: "https://images.unsplash.com/photo-1621303837174-89787a7d4729",
      },

      {
        id: "food_012",
        name: "Cold Coffee",
        description: "Chilled creamy coffee topped with ice cream.",
        price: 129,
        rating: 4.6,
        isVeg: true,
        bestseller: false,
        image: "https://images.unsplash.com/photo-1517701604599-bb29b565090c",
      },
    ],
  },
];
